### ISSUE TITLE
Error during installation add on

### ISSUE THREAD

**Issue by Rijnme** [Skons/hassio-addons#61]
Hello,

When I want to install the add-on I get the following error message: 

<img width="579" alt="Scherm­afbeelding 2023-12-16 om 19 30 05" src="https://github.com/Skons/hassio-addons/assets/142396941/2e9ae8cf-3404-4b68-b978-f88e18184e08">

Can you help me with this issue?

**Comment by Skons** [comment]
Are you still having this issue? If so, check these logs
Go to Settings -> System -> Logs. Select supervisor at the top right and show the error that is probably there?

On what kind of machine are you installing the addon?

**Comment by Rijnme** [comment]
Hello, thankyou for the reply. Yes I am still struggling with this issue. I am using this PC: https://www.robbshop.nl/intel-minipc-inclusief-home-assistant

see below for the error message:

24-01-15 16:58:01 INFO (MainThread) [supervisor.store] Loading add-ons from store: 81 all - 0 new - 0 remove
24-01-15 16:58:01 INFO (MainThread) [supervisor.store] Loading add-ons from store: 81 all - 0 new - 0 remove
24-01-15 16:59:06 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
24-01-15 16:59:36 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
24-01-15 17:03:57 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: f5a8083e_dutch_gas_prices
24-01-15 17:03:57 INFO (MainThread) [supervisor.docker.addon] Starting build for f5a8083e/amd64-addon-dutch_gas_prices:2023.10.15.1
24-01-15 17:04:09 ERROR (MainThread) [supervisor.docker.addon] Can't build f5a8083e/amd64-addon-dutch_gas_prices:2023.10.15.1: The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies         tesseract-ocr         tesseract-ocr-dev         jpeg-dev         libjpeg         zlib-dev         gcc         libc-dev' returned a non-zero code: 8
24-01-15 17:04:09 ERROR (MainThread) [supervisor.docker.addon] Build log: 
Step 1/31 : ARG BUILD_FROM=ghcr.io/hassio-addons/base-python/amd64:11.0.6


Step 2/31 : FROM ${BUILD_FROM}


 ---> 88acd1406c7b

Step 3/31 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]


 ---> Using cache

 ---> 5170f52d7c37

Step 4/31 : ARG BUILD_ARCH=amd64


 ---> Using cache

 ---> 3752777f893d

Step 5/31 : COPY rootfs/app /app


 ---> Using cache

 ---> f564f1a5889c

Step 6/31 : COPY rootfs/run.sh /


 ---> Using cache

 ---> efeabe33cf2c

Step 7/31 : RUN     apk del musl


 ---> Using cache

 ---> f3d58fe3a14c

Step 8/31 : ARG TARGETARCH


 ---> Using cache

 ---> 4c6e4c3467a1

Step 9/31 : RUN arch=$TARGETARCH     && if [ "$TARGETARCH" = "armv7" ]; then RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.17/community' >> /etc/apk/repositories; fi


 ---> Using cache

 ---> a8d0cfa73380

Step 10/31 : RUN     apk add --no-cache --virtual .build-dependencies         tesseract-ocr         tesseract-ocr-dev         jpeg-dev         libjpeg         zlib-dev         gcc         libc-dev


 ---> Running in 1bb277915856

fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz

WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)

fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz

WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/community: temporary error (try again later)

ERROR: unable to select packages:
  .build-dependencies-20240115.160408:
    masked in: cache
    satisfies: world[.build-dependencies=20240115.160408]
  tesseract-ocr (no such package):
    required by: .build-dependencies-20240115.160408[tesseract-ocr]
  tesseract-ocr-dev (no such package):
    required by: .build-dependencies-20240115.160408[tesseract-ocr-dev]
  jpeg-dev (no such package):
    required by: .build-dependencies-20240115.160408[jpeg-dev]
  libjpeg (no such package):
    required by: .build-dependencies-20240115.160408[libjpeg]

  zlib-dev (no such package):
    required by: .build-dependencies-20240115.160408[zlib-dev]
  gcc (no such package):
    required by: .build-dependencies-20240115.160408[gcc]
  libc-dev (no such package):
    required by: .build-dependencies-20240115.160408[libc-dev]

Removing intermediate container 1bb277915856

**Comment by Skons** [comment]
Your log mentions you cannot reach https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/. Does your HA have open internet? Do you have issues reaching that address?

This is your error
tesseract-ocr (no such package):
But your package that should be installed is this one
https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/tesseract-ocr-5.3.3-r1.apk

**Comment by Rijnme** [comment]
Yes I have open internet and I can reach that adress without any issues

**Comment by Skons** [comment]
It's weird that the packages can't be downloaded while internet is open. I tried to replicatie your issue, but mij x86 machine installs the addon perfectly. Do you have the terminal & ssh addon installed? maybe you could try to execute this command in that terminal:
```
wget https://dl-cdn.alpinelinux.org
```
it will show you an index.html, and i hope an error if it did not work. You can remote the index.html afterwards with
```
rm index.html
```

**Comment by Rijnme** [comment]
Hello Kevin,

I don’t get any error message when I execute the command. It gives me a 100% score.

**Comment by Skons** [comment]
I just released an update that hopefully solves your problem, could you try again?

**Comment by Rijnme** [comment]
Hi Kevin,I am sorry but it is still not working…Met vriendelijke groet,Menno van RijnOp 25 jan 2024 om 16:46 heeft Kevin Temming ***@***.***> het volgende geschreven:﻿
I just released an update that hopefully solves your problem, could you try again?

**Comment by Skons** [comment]
Did you make sure you had the latest version? And was it the same error?
